name: Publish Advent of Code task

on:
 schedule:
   # Every day at half an hour before Midnight EST (UTC-5) from 1 to 25 December
   - cron: '30 4 1-25 12 *'
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install requests
      - env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_AOC }}
        run: ./algo-club/advent-of-code-notify.py
