name: Publish Advent of Code task

on:
 schedule:
   # Every day at 00:01 EST (UTC-5) from 1 to 25 December every year
   - cron: '1 5 1-25 12 *'
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_AOC }}
        run: ./algo-club/advent-of-code-notify.py
