name: Publish Advent of Code task

on:
 schedule:
   # Every day at half an hour before Midnight EST (UTC-5) from 1 to 25 December
   - cron: '30 4 1-25 12 *'
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.AOC_TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.AOC_TELEGRAM_CHAT_ID }}
        run: ./algo-club/advent-of-code-notify.py
