name: Auto approve

on:
  pull_request_target:
    types: [opened, labeled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: github.actor == 'dependabot[bot]' || contains(github.event.pull_request.labels.*.name, 'ship!')
    steps:
      - name: Approve
        run: gh pr review "${{ github.event.pull_request.number }}" --approve --body "Ship it!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge "${{ github.event.pull_request.number }}" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
